name: rocket-tensorflow-hdfs

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.9.7
  - pip=21.2.4
  - pip:
      - mlflow==2.6.0
      - tensorflow==2.11.0
      - tensorflow-io==0.25.0